# Generated by Django 3.1.3 on 2021-04-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailfields',
            name='form_message',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
